### ISSUE TITLE
Adding docker-options as an official plugin

### ISSUE THREAD

**Issue by josegonzalez** [dyson/dokku-docker-options#6]
Would you be okay with us adding this as an official plugin in an upcoming release?

**Comment by dyson** [comment]
Yeah for sure, that would save me installing it all the time! I better get a move on and update it to support the docker-args changes that are coming up.

**Comment by josegonzalez** [comment]
Would also be good if you could remove the setup that happens in the `command` file. Most of that stuff is inlined. Fine if not, I'll probably take a gander to ensure we have it similar to the other official plugins :)

**Comment by dyson** [comment]
Yep, I'll create a new branch and reference this issue in it so you guys can review it and make sure it fit's in with coding style and everything else.

**Comment by dyson** [comment]
Hey @josegonzalez @michaelshobbs I have created another branch with a start to an official plugin based on the new phases.

Let me know what your thoughts are and I'll keep working it until we get it how you guys want.

https://github.com/dyson/dokku-docker-options/tree/dokku-merge

**Comment by dyson** [comment]
Also can you guys let me know on your thoughts of this issue https://github.com/dyson/dokku-docker-options/issues/3#issuecomment-85368015.

**Comment by michaelshobbs** [comment]
I might make those softlinks but that's just me. That's a lot of code-dupe :smile:

**Comment by dyson** [comment]
Yeah code dupe is cleared reduced a little now. I hadn't thought of the best solution for that yet and I think I have a reasonable compromise, although there is still a little bit.

We can't just softlink the different phases as we need to know what file to read the options from as each phase has it's own file for options (DOCKER_OPTIONS_BUILD, DOCKER_OPTIONS_DEPLOY and DOCKER_OPTIONS_RUN) so that you can set different options for each phase if need be.

We could also go down the path of having one file store it all, but personally I like the idea that the file contains only the options without prefixing a phase or creating some other way to group the options into different phases in the one file.

**Comment by michaelshobbs** [comment]
Oh yeah sorry I missed the whole filename bit. My bad. If you wanted to get your code dupe down to zero, you could probably do something like

```
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/common-docker-args"

STDIN=$(cat)
APP="$1"

case "$0" in
  *docker-args-build)
    PHASE=build
    ;;
  *docker-args-deploy)
    PHASE=deploy
    ;;
  *docker-args-run)
    PHASE=run
    ;;
esac

FILE_PREFIX="DOCKER_OPTIONS_"
PHASE_FILE_PATH="${DOKKU_ROOT}/${APP}/${FILE_PREFIX}${PHASE}"

output=""

get_options

echo "$STDIN$output"
```

**Comment by dyson** [comment]
Oh of course! Yeah I didn't even think about getting the name of the file. Brilliant. I'll update it now and remove the common file althogether.

**Comment by dyson** [comment]
Updated: https://github.com/dyson/dokku-docker-options/commit/78647a06d24ecda592d2b22f790e87f29575c277

Last thing I was thinking of adding was accepting the phases as a comma seperated list when running commands so you can set and remove options for multiple phases at once.

For example this would add the options to both deploy and run phases.
```
$ dokku docker-options:add myapp deploy,run -v host/dir:container/dir
```

Running the command with no phase or options whould list all options for all phases.
```
$ dokku docker-options myapp
Build options:
    -link link_name:alias

Run options:
    -v host/dir:container/dir
    -link link_name:alias
```

Finally, during build we probably should display what arguments have been passed. How does something like this look?
```
...

-----> Releasing hello-rack ...
-----> Deploying hello-rack ...
-----> Using Docker options
       -v host/dir:container/dir
       -link link_name:alias
-----> Running pre-flight checks
       CHECKS file not found in container: running simple container check...
-----> Waiting for 35 seconds ...

...
```

**Comment by josegonzalez** [comment]
I'd probably hide the docker options behind a flag. That's a personal choice though.

**Comment by dyson** [comment]
Yep, good idea @josegonzalez. After all, that's what flags are for.

I might be totally off the mark but were you thinking of something like this?

```
$ dokku docker-options:add myapp --deploy --build -v host/dir:container/dir
```

**Comment by josegonzalez** [comment]
Oh no, I meant outputting them in the deploy logs should be behind an env var.

**Comment by dyson** [comment]
Ah right, too easy.

**Comment by josegonzalez** [comment]
And its official! @dyson might want to mark this as deprecated.
