### ISSUE TITLE
"Phase(s) must be one of [build deploy run]"

### ISSUE THREAD

**Issue by busla** [dyson/dokku-docker-options#9]
Am I completely misunderstanding the docs?

This is my command: `dokku docker-options:add myapp  "-link my-other-app:some-alias"` ?

It returns: `"Phase(s) must be one of [build deploy run]"`

**Comment by dyson** [comment]
Hi Busla,

It looks like you are running the newer version of docker-options which was merged into dokku. This branch and it's documentation is depreciated. 

Docker options can be added to 3 different phases individually now. Perviously they weren't seperated which caused problems and reduced the ability for fine grain control.

Here are the current docs: http://progrium.viewdocs.io/dokku/docker-options/ . 

So you need to specify during which phase you would like the option to be added too. You can add it to multiple phases by using a comma separated list.

For example: `dokku docker-options:add myapp run "-link my-other-app:some-alias"`
or: `dokku docker-options:add myapp deploy,run "-link my-other-app:some-alias"`

**Comment by busla** [comment]
Thanks mate, figured this out the day after but totally forgot to report back :-)
